---
# tasks file for route53
- community.aws.route53:
    state: present
    zone: faizanulhaqtest.ml
    record: ansible.faizanulhaqtest.ml
    type: A
    value: "{{ alb_info.dns_name }}"
    alias: True
    alias_hosted_zone_id: Z1LMS91P8CMLE5
    alias_evaluate_target_health: True
